# -*- coding: utf-8 -*-
"""Exercise_1_Week1Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JUqK3KQ5NDOxaz41SmKt4pQuiW4R6XkB

Exercise 1
"""

from datetime import datetime

def age_calculator():
    try:
        # Ask user for birth date
        birth_str = input("Enter your birth date (mm/dd/yyyy): ").strip()

        # Validate input format and date
        try:
            birth_date = datetime.strptime(birth_str, "%m/%d/%Y")
        except ValueError:
            print("Invalid date format or invalid date.")
            return

        # Calculate age
        today = datetime.today()
        age = today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))

        # Convert and display birthdate in European format
        european_format = birth_date.strftime("%d/%m/%Y")

        # Display results
        print(f"Your birth date (European format): {european_format}")
        print(f"Your current age: {age} years")

    except Exception as e:
        # Handle unexpected errors
        print("An unexpected error occurred:", str(e))

# Run the program
if __name__ == "__main__":
    age_calculator()